CREATE TABLE IF NOT EXISTS USERS (
    U_ID INTEGER PRIMARY KEY,
    F_NAME TEXT NOT NULL,
    L_NAME TEXT NOT NULL,
    PASSWD TEXT NOT NULL,
    CONSTRAINT NAMES UNIQUE (F_NAME, L_NAME)
);

CREATE TABLE IF NOT EXISTS USER_SESSIONS (
    U_ID INTEGER PRIMARY KEY,
    JWT TEXT NOT NULL,
    AT_TIME INTEGER NOT NULL,
    
    FOREIGN KEY (U_ID) REFERENCES USERS (U_ID) on delete cascade on update cascade
);

CREATE TABLE IF NOT EXISTS NODES (
    N_ID INTEGER PRIMARY KEY,
    X REAL NOT NULL,
    Y REAL NOT NULL,
    Z INTEGER NOT NULL DEFAULT 1,
    NODE_NAME TEXT NOT NULL,
    NODE_GROUP TEXT DEFAULT NULL,
    KIND INTEGER
);

CREATE TABLE IF NOT EXISTS NODE_TAGS (
    N_ID INTEGER PRIMARY KEY,
    TAG TEXT NOT NULL,
    
    FOREIGN KEY (N_ID) REFERENCES NODES (N_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS EDGES (
    SOURCE INTEGER NOT NULL,
    DESTIONATION INTEGER NOT NULL,

    CONSTRAINT PK1 PRIMARY KEY (SOURCE, DESTIONATION),

    FOREIGN KEY (SOURCE) REFERENCES NODES (N_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (DESTIONATION) REFERENCES NODES (N_ID) ON DELETE CASCADE ON UPDATE CASCADE
);